/********************************************************************************
** Form generated from reading UI file 'mainwindow.ui'
**
** Created by: Qt User Interface Compiler version 6.4.0
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINWINDOW_H
#define UI_MAINWINDOW_H

#include <QtCore/QVariant>
#include <QtWidgets/QApplication>
#include <QtWidgets/QComboBox>
#include <QtWidgets/QGroupBox>
#include <QtWidgets/QHBoxLayout>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QStackedWidget>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QToolButton>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QWidget *centralwidget;
    QStackedWidget *stackedWidget;
    QWidget *main_page;
    QLabel *title;
    QPushButton *pushButton;
    QWidget *main_menu;
    QPushButton *quizBtn;
    QPushButton *revBtn;
    QPushButton *ldrbrdBtn;
    QWidget *category;
    QLabel *cat_title;
    QGroupBox *groupBox;
    QPushButton *alg_btn;
    QPushButton *geo_btn;
    QPushButton *trig_btn;
    QPushButton *cus_btn;
    QPushButton *back_btn;
    QWidget *difficulty;
    QLabel *difficulty_lbl;
    QPushButton *easyBtn;
    QPushButton *mediumBtn;
    QPushButton *difficultBtn;
    QPushButton *backBtn;
    QPushButton *main_menu_2;
    QWidget *instruction_win;
    QPushButton *okaybtn;
    QLabel *instruction;
    QWidget *quiz;
    QLabel *diff_label;
    QLabel *score;
    QLabel *time;
    QStackedWidget *quizBox;
    QWidget *easy;
    QGroupBox *easyBox;
    QLabel *eq;
    QPushButton *t;
    QPushButton *f;
    QWidget *medium;
    QGroupBox *mediumBox;
    QLabel *mq;
    QPushButton *a;
    QPushButton *b;
    QPushButton *c;
    QPushButton *d;
    QWidget *hard;
    QGroupBox *hardBox;
    QLabel *hq;
    QLineEdit *ans_inp;
    QPushButton *submit_btn;
    QLabel *timer;
    QPushButton *pause_btn;
    QLabel *label;
    QLabel *label_2;
    QLabel *scoreLbl;
    QWidget *pause_win;
    QLabel *pause_lbl;
    QPushButton *resumeBtn;
    QPushButton *retryBtn;
    QPushButton *menuBtnP;
    QWidget *result;
    QLabel *remarks;
    QLabel *scr_lbl;
    QLabel *ca_lbl;
    QLabel *c_ans;
    QLabel *scre;
    QLabel *name;
    QLineEdit *name_inp;
    QWidget *auth;
    QStackedWidget *ls_box;
    QWidget *login_top;
    QLabel *name_lbl;
    QLabel *pass_lbl;
    QPushButton *login_btn;
    QLineEdit *name_inp_auth;
    QLineEdit *pass_inp_auth;
    QLabel *label_3;
    QLabel *error_msg_l;
    QWidget *sign_up_top;
    QLabel *name_lbl_s;
    QLabel *pass_lbl_s;
    QLabel *pass_lbl_s_c;
    QPushButton *signup_btn;
    QLineEdit *name_inp_auth_s;
    QLineEdit *pass_inp_auth_s;
    QLineEdit *cpass_;
    QLabel *label_4;
    QLabel *error_msg;
    QPushButton *login_sec;
    QPushButton *sign_sec;
    QPushButton *back_btn_c;
    QWidget *firstform;
    QPushButton *BackBtn;
    QPushButton *pushButton_2;
    QLabel *label_7;
    QLineEdit *lineEdit_4;
    QWidget *layoutWidget;
    QHBoxLayout *horizontalLayout_2;
    QHBoxLayout *horizontalLayout;
    QLabel *label_8;
    QLineEdit *reviewer;
    QToolButton *toolButton;
    QWidget *layoutWidget1;
    QHBoxLayout *horizontalLayout_3;
    QLabel *label_6;
    QLineEdit *lineEdit_2;
    QWidget *layoutWidget2;
    QHBoxLayout *horizontalLayout_4;
    QLabel *label_5;
    QLineEdit *name_1;
    QLabel *error1;
    QWidget *secondform;
    QComboBox *comboBox;
    QStackedWidget *stackedWidget_2;
    QWidget *page;
    QPushButton *trueBtn;
    QPushButton *falseBtn;
    QLabel *error_msg1;
    QWidget *page_2;
    QPushButton *a_btn;
    QPushButton *b_btn;
    QPushButton *c_btn;
    QPushButton *d_btn;
    QLineEdit *aLineEdit;
    QLineEdit *bLineEdit;
    QLineEdit *cLineEdit;
    QLineEdit *dLineEdit;
    QWidget *page_3;
    QLineEdit *hardlineEdit;
    QLineEdit *lineEdit;
    QLabel *label_9;
    QPushButton *Add;
    QPushButton *pushButton_9;
    QLabel *cat;
    QLabel *name_2;
    QLabel *q_no;
    QWidget *confirmation;
    QStatusBar *statusbar;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName("MainWindow");
        MainWindow->resize(373, 371);
        centralwidget = new QWidget(MainWindow);
        centralwidget->setObjectName("centralwidget");
        stackedWidget = new QStackedWidget(centralwidget);
        stackedWidget->setObjectName("stackedWidget");
        stackedWidget->setGeometry(QRect(0, 0, 371, 371));
        main_page = new QWidget();
        main_page->setObjectName("main_page");
        title = new QLabel(main_page);
        title->setObjectName("title");
        title->setGeometry(QRect(150, 90, 63, 20));
        pushButton = new QPushButton(main_page);
        pushButton->setObjectName("pushButton");
        pushButton->setGeometry(QRect(120, 220, 93, 29));
        stackedWidget->addWidget(main_page);
        main_menu = new QWidget();
        main_menu->setObjectName("main_menu");
        quizBtn = new QPushButton(main_menu);
        quizBtn->setObjectName("quizBtn");
        quizBtn->setGeometry(QRect(30, 100, 301, 41));
        revBtn = new QPushButton(main_menu);
        revBtn->setObjectName("revBtn");
        revBtn->setGeometry(QRect(30, 160, 301, 41));
        ldrbrdBtn = new QPushButton(main_menu);
        ldrbrdBtn->setObjectName("ldrbrdBtn");
        ldrbrdBtn->setGeometry(QRect(30, 220, 301, 41));
        stackedWidget->addWidget(main_menu);
        category = new QWidget();
        category->setObjectName("category");
        cat_title = new QLabel(category);
        cat_title->setObjectName("cat_title");
        cat_title->setGeometry(QRect(140, 20, 111, 31));
        QFont font;
        font.setPointSize(12);
        cat_title->setFont(font);
        cat_title->setAlignment(Qt::AlignCenter);
        groupBox = new QGroupBox(category);
        groupBox->setObjectName("groupBox");
        groupBox->setGeometry(QRect(130, 70, 120, 251));
        alg_btn = new QPushButton(groupBox);
        alg_btn->setObjectName("alg_btn");
        alg_btn->setGeometry(QRect(10, 30, 93, 29));
        geo_btn = new QPushButton(groupBox);
        geo_btn->setObjectName("geo_btn");
        geo_btn->setGeometry(QRect(10, 70, 93, 29));
        trig_btn = new QPushButton(groupBox);
        trig_btn->setObjectName("trig_btn");
        trig_btn->setGeometry(QRect(10, 110, 101, 29));
        cus_btn = new QPushButton(groupBox);
        cus_btn->setObjectName("cus_btn");
        cus_btn->setGeometry(QRect(10, 150, 101, 29));
        back_btn = new QPushButton(groupBox);
        back_btn->setObjectName("back_btn");
        back_btn->setGeometry(QRect(10, 190, 101, 29));
        stackedWidget->addWidget(category);
        difficulty = new QWidget();
        difficulty->setObjectName("difficulty");
        difficulty_lbl = new QLabel(difficulty);
        difficulty_lbl->setObjectName("difficulty_lbl");
        difficulty_lbl->setGeometry(QRect(130, 20, 111, 41));
        difficulty_lbl->setFont(font);
        difficulty_lbl->setLayoutDirection(Qt::LeftToRight);
        difficulty_lbl->setScaledContents(false);
        difficulty_lbl->setAlignment(Qt::AlignCenter);
        easyBtn = new QPushButton(difficulty);
        easyBtn->setObjectName("easyBtn");
        easyBtn->setGeometry(QRect(30, 70, 301, 41));
        mediumBtn = new QPushButton(difficulty);
        mediumBtn->setObjectName("mediumBtn");
        mediumBtn->setGeometry(QRect(30, 120, 301, 41));
        difficultBtn = new QPushButton(difficulty);
        difficultBtn->setObjectName("difficultBtn");
        difficultBtn->setGeometry(QRect(30, 170, 301, 41));
        backBtn = new QPushButton(difficulty);
        backBtn->setObjectName("backBtn");
        backBtn->setGeometry(QRect(30, 220, 301, 41));
        main_menu_2 = new QPushButton(difficulty);
        main_menu_2->setObjectName("main_menu_2");
        main_menu_2->setGeometry(QRect(30, 270, 301, 41));
        stackedWidget->addWidget(difficulty);
        instruction_win = new QWidget();
        instruction_win->setObjectName("instruction_win");
        okaybtn = new QPushButton(instruction_win);
        okaybtn->setObjectName("okaybtn");
        okaybtn->setGeometry(QRect(130, 230, 93, 29));
        instruction = new QLabel(instruction_win);
        instruction->setObjectName("instruction");
        instruction->setGeometry(QRect(70, 70, 221, 131));
        stackedWidget->addWidget(instruction_win);
        quiz = new QWidget();
        quiz->setObjectName("quiz");
        diff_label = new QLabel(quiz);
        diff_label->setObjectName("diff_label");
        diff_label->setGeometry(QRect(10, 50, 63, 20));
        score = new QLabel(quiz);
        score->setObjectName("score");
        score->setGeometry(QRect(10, 70, 63, 20));
        time = new QLabel(quiz);
        time->setObjectName("time");
        time->setGeometry(QRect(10, 110, 63, 20));
        quizBox = new QStackedWidget(quiz);
        quizBox->setObjectName("quizBox");
        quizBox->setGeometry(QRect(30, 130, 311, 211));
        quizBox->setStyleSheet(QString::fromUtf8("background-color: rgb(170, 255, 255);"));
        easy = new QWidget();
        easy->setObjectName("easy");
        easyBox = new QGroupBox(easy);
        easyBox->setObjectName("easyBox");
        easyBox->setGeometry(QRect(10, 20, 281, 181));
        eq = new QLabel(easyBox);
        eq->setObjectName("eq");
        eq->setGeometry(QRect(30, 30, 211, 51));
        t = new QPushButton(easyBox);
        t->setObjectName("t");
        t->setGeometry(QRect(20, 140, 93, 29));
        f = new QPushButton(easyBox);
        f->setObjectName("f");
        f->setGeometry(QRect(160, 140, 93, 29));
        quizBox->addWidget(easy);
        medium = new QWidget();
        medium->setObjectName("medium");
        mediumBox = new QGroupBox(medium);
        mediumBox->setObjectName("mediumBox");
        mediumBox->setGeometry(QRect(20, 40, 271, 201));
        mq = new QLabel(mediumBox);
        mq->setObjectName("mq");
        mq->setGeometry(QRect(30, 30, 211, 31));
        a = new QPushButton(mediumBox);
        a->setObjectName("a");
        a->setGeometry(QRect(20, 70, 231, 29));
        b = new QPushButton(mediumBox);
        b->setObjectName("b");
        b->setGeometry(QRect(20, 100, 231, 29));
        c = new QPushButton(mediumBox);
        c->setObjectName("c");
        c->setGeometry(QRect(20, 130, 231, 29));
        d = new QPushButton(mediumBox);
        d->setObjectName("d");
        d->setGeometry(QRect(20, 160, 231, 29));
        quizBox->addWidget(medium);
        hard = new QWidget();
        hard->setObjectName("hard");
        hardBox = new QGroupBox(hard);
        hardBox->setObjectName("hardBox");
        hardBox->setGeometry(QRect(20, 30, 271, 201));
        hq = new QLabel(hardBox);
        hq->setObjectName("hq");
        hq->setGeometry(QRect(40, 30, 201, 41));
        ans_inp = new QLineEdit(hardBox);
        ans_inp->setObjectName("ans_inp");
        ans_inp->setGeometry(QRect(30, 110, 191, 31));
        ans_inp->setStyleSheet(QString::fromUtf8("background-color: rgb(255, 255, 255);"));
        submit_btn = new QPushButton(hardBox);
        submit_btn->setObjectName("submit_btn");
        submit_btn->setGeometry(QRect(80, 150, 93, 29));
        quizBox->addWidget(hard);
        timer = new QLabel(quiz);
        timer->setObjectName("timer");
        timer->setGeometry(QRect(120, 20, 161, 51));
        pause_btn = new QPushButton(quiz);
        pause_btn->setObjectName("pause_btn");
        pause_btn->setGeometry(QRect(10, 0, 93, 29));
        label = new QLabel(quiz);
        label->setObjectName("label");
        label->setGeometry(QRect(220, 10, 91, 20));
        label_2 = new QLabel(quiz);
        label_2->setObjectName("label_2");
        label_2->setGeometry(QRect(320, 10, 63, 20));
        scoreLbl = new QLabel(quiz);
        scoreLbl->setObjectName("scoreLbl");
        scoreLbl->setGeometry(QRect(50, 70, 63, 20));
        stackedWidget->addWidget(quiz);
        pause_win = new QWidget();
        pause_win->setObjectName("pause_win");
        pause_lbl = new QLabel(pause_win);
        pause_lbl->setObjectName("pause_lbl");
        pause_lbl->setGeometry(QRect(110, 20, 141, 71));
        resumeBtn = new QPushButton(pause_win);
        resumeBtn->setObjectName("resumeBtn");
        resumeBtn->setGeometry(QRect(130, 130, 93, 29));
        retryBtn = new QPushButton(pause_win);
        retryBtn->setObjectName("retryBtn");
        retryBtn->setGeometry(QRect(130, 170, 93, 29));
        menuBtnP = new QPushButton(pause_win);
        menuBtnP->setObjectName("menuBtnP");
        menuBtnP->setGeometry(QRect(130, 210, 93, 29));
        stackedWidget->addWidget(pause_win);
        result = new QWidget();
        result->setObjectName("result");
        remarks = new QLabel(result);
        remarks->setObjectName("remarks");
        remarks->setGeometry(QRect(130, 40, 111, 51));
        scr_lbl = new QLabel(result);
        scr_lbl->setObjectName("scr_lbl");
        scr_lbl->setGeometry(QRect(30, 160, 71, 31));
        ca_lbl = new QLabel(result);
        ca_lbl->setObjectName("ca_lbl");
        ca_lbl->setGeometry(QRect(30, 120, 121, 31));
        c_ans = new QLabel(result);
        c_ans->setObjectName("c_ans");
        c_ans->setGeometry(QRect(170, 130, 63, 20));
        scre = new QLabel(result);
        scre->setObjectName("scre");
        scre->setGeometry(QRect(170, 160, 63, 20));
        name = new QLabel(result);
        name->setObjectName("name");
        name->setGeometry(QRect(30, 210, 63, 20));
        name_inp = new QLineEdit(result);
        name_inp->setObjectName("name_inp");
        name_inp->setGeometry(QRect(160, 210, 113, 26));
        stackedWidget->addWidget(result);
        auth = new QWidget();
        auth->setObjectName("auth");
        ls_box = new QStackedWidget(auth);
        ls_box->setObjectName("ls_box");
        ls_box->setGeometry(QRect(30, 80, 321, 251));
        login_top = new QWidget();
        login_top->setObjectName("login_top");
        name_lbl = new QLabel(login_top);
        name_lbl->setObjectName("name_lbl");
        name_lbl->setGeometry(QRect(20, 40, 63, 20));
        pass_lbl = new QLabel(login_top);
        pass_lbl->setObjectName("pass_lbl");
        pass_lbl->setGeometry(QRect(10, 100, 91, 20));
        login_btn = new QPushButton(login_top);
        login_btn->setObjectName("login_btn");
        login_btn->setGeometry(QRect(100, 180, 93, 29));
        login_btn->setStyleSheet(QString::fromUtf8(""));
        name_inp_auth = new QLineEdit(login_top);
        name_inp_auth->setObjectName("name_inp_auth");
        name_inp_auth->setGeometry(QRect(90, 40, 113, 26));
        pass_inp_auth = new QLineEdit(login_top);
        pass_inp_auth->setObjectName("pass_inp_auth");
        pass_inp_auth->setGeometry(QRect(90, 100, 113, 26));
        pass_inp_auth->setEchoMode(QLineEdit::Password);
        label_3 = new QLabel(login_top);
        label_3->setObjectName("label_3");
        label_3->setGeometry(QRect(10, 220, 131, 20));
        error_msg_l = new QLabel(login_top);
        error_msg_l->setObjectName("error_msg_l");
        error_msg_l->setGeometry(QRect(30, 150, 271, 20));
        ls_box->addWidget(login_top);
        sign_up_top = new QWidget();
        sign_up_top->setObjectName("sign_up_top");
        name_lbl_s = new QLabel(sign_up_top);
        name_lbl_s->setObjectName("name_lbl_s");
        name_lbl_s->setGeometry(QRect(20, 70, 63, 20));
        pass_lbl_s = new QLabel(sign_up_top);
        pass_lbl_s->setObjectName("pass_lbl_s");
        pass_lbl_s->setGeometry(QRect(20, 110, 81, 20));
        pass_lbl_s_c = new QLabel(sign_up_top);
        pass_lbl_s_c->setObjectName("pass_lbl_s_c");
        pass_lbl_s_c->setGeometry(QRect(20, 150, 131, 20));
        signup_btn = new QPushButton(sign_up_top);
        signup_btn->setObjectName("signup_btn");
        signup_btn->setGeometry(QRect(110, 210, 93, 29));
        name_inp_auth_s = new QLineEdit(sign_up_top);
        name_inp_auth_s->setObjectName("name_inp_auth_s");
        name_inp_auth_s->setGeometry(QRect(170, 70, 113, 26));
        pass_inp_auth_s = new QLineEdit(sign_up_top);
        pass_inp_auth_s->setObjectName("pass_inp_auth_s");
        pass_inp_auth_s->setGeometry(QRect(170, 110, 113, 26));
        pass_inp_auth_s->setEchoMode(QLineEdit::Password);
        cpass_ = new QLineEdit(sign_up_top);
        cpass_->setObjectName("cpass_");
        cpass_->setGeometry(QRect(170, 150, 113, 26));
        cpass_->setEchoMode(QLineEdit::Password);
        label_4 = new QLabel(sign_up_top);
        label_4->setObjectName("label_4");
        label_4->setGeometry(QRect(20, 220, 111, 20));
        error_msg = new QLabel(sign_up_top);
        error_msg->setObjectName("error_msg");
        error_msg->setGeometry(QRect(20, 190, 271, 20));
        ls_box->addWidget(sign_up_top);
        login_sec = new QPushButton(auth);
        login_sec->setObjectName("login_sec");
        login_sec->setGeometry(QRect(30, 40, 151, 29));
        login_sec->setStyleSheet(QString::fromUtf8(""));
        sign_sec = new QPushButton(auth);
        sign_sec->setObjectName("sign_sec");
        sign_sec->setGeometry(QRect(180, 40, 151, 29));
        back_btn_c = new QPushButton(auth);
        back_btn_c->setObjectName("back_btn_c");
        back_btn_c->setGeometry(QRect(10, 0, 93, 29));
        stackedWidget->addWidget(auth);
        firstform = new QWidget();
        firstform->setObjectName("firstform");
        BackBtn = new QPushButton(firstform);
        BackBtn->setObjectName("BackBtn");
        BackBtn->setGeometry(QRect(10, 10, 93, 29));
        pushButton_2 = new QPushButton(firstform);
        pushButton_2->setObjectName("pushButton_2");
        pushButton_2->setGeometry(QRect(250, 310, 93, 29));
        label_7 = new QLabel(firstform);
        label_7->setObjectName("label_7");
        label_7->setGeometry(QRect(30, 200, 58, 26));
        lineEdit_4 = new QLineEdit(firstform);
        lineEdit_4->setObjectName("lineEdit_4");
        lineEdit_4->setGeometry(QRect(100, 200, 231, 91));
        lineEdit_4->setFocusPolicy(Qt::StrongFocus);
        lineEdit_4->setReadOnly(false);
        layoutWidget = new QWidget(firstform);
        layoutWidget->setObjectName("layoutWidget");
        layoutWidget->setGeometry(QRect(30, 150, 252, 30));
        horizontalLayout_2 = new QHBoxLayout(layoutWidget);
        horizontalLayout_2->setObjectName("horizontalLayout_2");
        horizontalLayout_2->setContentsMargins(0, 0, 0, 0);
        horizontalLayout = new QHBoxLayout();
        horizontalLayout->setObjectName("horizontalLayout");
        label_8 = new QLabel(layoutWidget);
        label_8->setObjectName("label_8");

        horizontalLayout->addWidget(label_8);

        reviewer = new QLineEdit(layoutWidget);
        reviewer->setObjectName("reviewer");

        horizontalLayout->addWidget(reviewer);

        toolButton = new QToolButton(layoutWidget);
        toolButton->setObjectName("toolButton");

        horizontalLayout->addWidget(toolButton);


        horizontalLayout_2->addLayout(horizontalLayout);

        layoutWidget1 = new QWidget(firstform);
        layoutWidget1->setObjectName("layoutWidget1");
        layoutWidget1->setGeometry(QRect(30, 100, 231, 28));
        horizontalLayout_3 = new QHBoxLayout(layoutWidget1);
        horizontalLayout_3->setObjectName("horizontalLayout_3");
        horizontalLayout_3->setContentsMargins(0, 0, 0, 0);
        label_6 = new QLabel(layoutWidget1);
        label_6->setObjectName("label_6");

        horizontalLayout_3->addWidget(label_6);

        lineEdit_2 = new QLineEdit(layoutWidget1);
        lineEdit_2->setObjectName("lineEdit_2");
        lineEdit_2->setFocusPolicy(Qt::StrongFocus);
        lineEdit_2->setReadOnly(false);

        horizontalLayout_3->addWidget(lineEdit_2);

        layoutWidget2 = new QWidget(firstform);
        layoutWidget2->setObjectName("layoutWidget2");
        layoutWidget2->setGeometry(QRect(30, 50, 171, 28));
        horizontalLayout_4 = new QHBoxLayout(layoutWidget2);
        horizontalLayout_4->setObjectName("horizontalLayout_4");
        horizontalLayout_4->setContentsMargins(0, 0, 0, 0);
        label_5 = new QLabel(layoutWidget2);
        label_5->setObjectName("label_5");

        horizontalLayout_4->addWidget(label_5);

        name_1 = new QLineEdit(layoutWidget2);
        name_1->setObjectName("name_1");
        name_1->setFocusPolicy(Qt::StrongFocus);
        name_1->setReadOnly(true);

        horizontalLayout_4->addWidget(name_1);

        error1 = new QLabel(firstform);
        error1->setObjectName("error1");
        error1->setGeometry(QRect(80, 310, 141, 20));
        stackedWidget->addWidget(firstform);
        secondform = new QWidget();
        secondform->setObjectName("secondform");
        comboBox = new QComboBox(secondform);
        comboBox->addItem(QString());
        comboBox->addItem(QString());
        comboBox->addItem(QString());
        comboBox->setObjectName("comboBox");
        comboBox->setGeometry(QRect(70, 60, 231, 26));
        stackedWidget_2 = new QStackedWidget(secondform);
        stackedWidget_2->setObjectName("stackedWidget_2");
        stackedWidget_2->setGeometry(QRect(30, 200, 311, 101));
        stackedWidget_2->setStyleSheet(QString::fromUtf8("background-color: rgb(170, 170, 255);"));
        page = new QWidget();
        page->setObjectName("page");
        trueBtn = new QPushButton(page);
        trueBtn->setObjectName("trueBtn");
        trueBtn->setGeometry(QRect(20, 40, 93, 29));
        trueBtn->setStyleSheet(QString::fromUtf8(""));
        falseBtn = new QPushButton(page);
        falseBtn->setObjectName("falseBtn");
        falseBtn->setGeometry(QRect(190, 40, 93, 29));
        falseBtn->setStyleSheet(QString::fromUtf8(""));
        error_msg1 = new QLabel(page);
        error_msg1->setObjectName("error_msg1");
        error_msg1->setGeometry(QRect(60, 80, 191, 20));
        stackedWidget_2->addWidget(page);
        page_2 = new QWidget();
        page_2->setObjectName("page_2");
        a_btn = new QPushButton(page_2);
        a_btn->setObjectName("a_btn");
        a_btn->setGeometry(QRect(20, 10, 31, 29));
        b_btn = new QPushButton(page_2);
        b_btn->setObjectName("b_btn");
        b_btn->setGeometry(QRect(20, 60, 31, 29));
        c_btn = new QPushButton(page_2);
        c_btn->setObjectName("c_btn");
        c_btn->setGeometry(QRect(170, 10, 31, 29));
        d_btn = new QPushButton(page_2);
        d_btn->setObjectName("d_btn");
        d_btn->setGeometry(QRect(170, 60, 31, 29));
        aLineEdit = new QLineEdit(page_2);
        aLineEdit->setObjectName("aLineEdit");
        aLineEdit->setGeometry(QRect(60, 10, 71, 31));
        bLineEdit = new QLineEdit(page_2);
        bLineEdit->setObjectName("bLineEdit");
        bLineEdit->setGeometry(QRect(60, 60, 71, 31));
        cLineEdit = new QLineEdit(page_2);
        cLineEdit->setObjectName("cLineEdit");
        cLineEdit->setGeometry(QRect(210, 10, 71, 31));
        dLineEdit = new QLineEdit(page_2);
        dLineEdit->setObjectName("dLineEdit");
        dLineEdit->setGeometry(QRect(210, 60, 71, 31));
        stackedWidget_2->addWidget(page_2);
        page_3 = new QWidget();
        page_3->setObjectName("page_3");
        hardlineEdit = new QLineEdit(page_3);
        hardlineEdit->setObjectName("hardlineEdit");
        hardlineEdit->setGeometry(QRect(20, 40, 271, 41));
        stackedWidget_2->addWidget(page_3);
        lineEdit = new QLineEdit(secondform);
        lineEdit->setObjectName("lineEdit");
        lineEdit->setGeometry(QRect(30, 90, 311, 111));
        label_9 = new QLabel(secondform);
        label_9->setObjectName("label_9");
        label_9->setGeometry(QRect(30, 80, 63, 20));
        Add = new QPushButton(secondform);
        Add->setObjectName("Add");
        Add->setGeometry(QRect(20, 310, 93, 29));
        pushButton_9 = new QPushButton(secondform);
        pushButton_9->setObjectName("pushButton_9");
        pushButton_9->setGeometry(QRect(270, 310, 93, 29));
        cat = new QLabel(secondform);
        cat->setObjectName("cat");
        cat->setGeometry(QRect(10, 10, 63, 20));
        name_2 = new QLabel(secondform);
        name_2->setObjectName("name_2");
        name_2->setGeometry(QRect(100, 10, 63, 20));
        q_no = new QLabel(secondform);
        q_no->setObjectName("q_no");
        q_no->setGeometry(QRect(190, 20, 91, 20));
        stackedWidget->addWidget(secondform);
        confirmation = new QWidget();
        confirmation->setObjectName("confirmation");
        stackedWidget->addWidget(confirmation);
        MainWindow->setCentralWidget(centralwidget);
        statusbar = new QStatusBar(MainWindow);
        statusbar->setObjectName("statusbar");
        MainWindow->setStatusBar(statusbar);

        retranslateUi(MainWindow);

        stackedWidget->setCurrentIndex(10);
        quizBox->setCurrentIndex(2);
        ls_box->setCurrentIndex(0);
        stackedWidget_2->setCurrentIndex(2);


        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QCoreApplication::translate("MainWindow", "trial", nullptr));
        title->setText(QCoreApplication::translate("MainWindow", "Trial", nullptr));
        pushButton->setText(QCoreApplication::translate("MainWindow", "Enter", nullptr));
        quizBtn->setText(QCoreApplication::translate("MainWindow", "Start Quiz", nullptr));
        revBtn->setText(QCoreApplication::translate("MainWindow", "Review", nullptr));
        ldrbrdBtn->setText(QCoreApplication::translate("MainWindow", "Leaderboards", nullptr));
        cat_title->setText(QCoreApplication::translate("MainWindow", "CATEGORY", nullptr));
        groupBox->setTitle(QString());
        alg_btn->setText(QCoreApplication::translate("MainWindow", "Algebra", nullptr));
        geo_btn->setText(QCoreApplication::translate("MainWindow", "Geometry", nullptr));
        trig_btn->setText(QCoreApplication::translate("MainWindow", "Trigonometry", nullptr));
        cus_btn->setText(QCoreApplication::translate("MainWindow", "Customized", nullptr));
        back_btn->setText(QCoreApplication::translate("MainWindow", "Back", nullptr));
        difficulty_lbl->setText(QCoreApplication::translate("MainWindow", "DIFFICULTY", nullptr));
        easyBtn->setText(QCoreApplication::translate("MainWindow", "Easy (True or False)", nullptr));
        mediumBtn->setText(QCoreApplication::translate("MainWindow", "Medium (Multiple Choice)", nullptr));
        difficultBtn->setText(QCoreApplication::translate("MainWindow", "Difficult (Identification)", nullptr));
        backBtn->setText(QCoreApplication::translate("MainWindow", "Back", nullptr));
        main_menu_2->setText(QCoreApplication::translate("MainWindow", "Main Menu", nullptr));
        okaybtn->setText(QCoreApplication::translate("MainWindow", "OK", nullptr));
        instruction->setText(QString());
        diff_label->setText(QCoreApplication::translate("MainWindow", "diff", nullptr));
        score->setText(QCoreApplication::translate("MainWindow", "Score:", nullptr));
        time->setText(QCoreApplication::translate("MainWindow", "Time", nullptr));
        easyBox->setTitle(QCoreApplication::translate("MainWindow", "Easy", nullptr));
        eq->setText(QCoreApplication::translate("MainWindow", "Question 1", nullptr));
        t->setText(QCoreApplication::translate("MainWindow", "true", nullptr));
        f->setText(QCoreApplication::translate("MainWindow", "False", nullptr));
        mediumBox->setTitle(QCoreApplication::translate("MainWindow", "Medium", nullptr));
        mq->setText(QCoreApplication::translate("MainWindow", "Question 2", nullptr));
        a->setText(QCoreApplication::translate("MainWindow", "A", nullptr));
        b->setText(QCoreApplication::translate("MainWindow", "B", nullptr));
        c->setText(QCoreApplication::translate("MainWindow", "C", nullptr));
        d->setText(QCoreApplication::translate("MainWindow", "D", nullptr));
        hardBox->setTitle(QCoreApplication::translate("MainWindow", "hard", nullptr));
        hq->setText(QCoreApplication::translate("MainWindow", "Question 1", nullptr));
        submit_btn->setText(QCoreApplication::translate("MainWindow", "Submit", nullptr));
        timer->setText(QCoreApplication::translate("MainWindow", "TextLabel", nullptr));
        pause_btn->setText(QCoreApplication::translate("MainWindow", "Pause", nullptr));
        label->setText(QCoreApplication::translate("MainWindow", "Prepared by:", nullptr));
        label_2->setText(QCoreApplication::translate("MainWindow", "Name", nullptr));
        scoreLbl->setText(QCoreApplication::translate("MainWindow", "scoreLbl", nullptr));
        pause_lbl->setText(QCoreApplication::translate("MainWindow", "Pause", nullptr));
        resumeBtn->setText(QCoreApplication::translate("MainWindow", "Resume", nullptr));
        retryBtn->setText(QCoreApplication::translate("MainWindow", "Retry", nullptr));
        menuBtnP->setText(QCoreApplication::translate("MainWindow", "Main Menu", nullptr));
        remarks->setText(QCoreApplication::translate("MainWindow", "Passed or Not", nullptr));
        scr_lbl->setText(QCoreApplication::translate("MainWindow", "Score:", nullptr));
        ca_lbl->setText(QCoreApplication::translate("MainWindow", "Correct Answer/s:", nullptr));
        c_ans->setText(QCoreApplication::translate("MainWindow", "...", nullptr));
        scre->setText(QCoreApplication::translate("MainWindow", "...", nullptr));
        name->setText(QCoreApplication::translate("MainWindow", "Name: ", nullptr));
        name_lbl->setText(QCoreApplication::translate("MainWindow", "name:", nullptr));
        pass_lbl->setText(QCoreApplication::translate("MainWindow", "password:", nullptr));
        login_btn->setText(QCoreApplication::translate("MainWindow", "Login", nullptr));
        label_3->setText(QCoreApplication::translate("MainWindow", "Check lang", nullptr));
        error_msg_l->setText(QString());
        name_lbl_s->setText(QCoreApplication::translate("MainWindow", "name:", nullptr));
        pass_lbl_s->setText(QCoreApplication::translate("MainWindow", "password:", nullptr));
        pass_lbl_s_c->setText(QCoreApplication::translate("MainWindow", "confirm password:", nullptr));
        signup_btn->setText(QCoreApplication::translate("MainWindow", "Sign Up", nullptr));
        label_4->setText(QCoreApplication::translate("MainWindow", "Insert into user", nullptr));
        error_msg->setText(QString());
        login_sec->setText(QCoreApplication::translate("MainWindow", "Login", nullptr));
        sign_sec->setText(QCoreApplication::translate("MainWindow", "Sign-up", nullptr));
        back_btn_c->setText(QCoreApplication::translate("MainWindow", "Back", nullptr));
        BackBtn->setText(QCoreApplication::translate("MainWindow", "Back", nullptr));
        pushButton_2->setText(QCoreApplication::translate("MainWindow", "Next", nullptr));
        label_7->setText(QCoreApplication::translate("MainWindow", "note", nullptr));
        lineEdit_4->setText(QString());
        label_8->setText(QCoreApplication::translate("MainWindow", "reviewer", nullptr));
        toolButton->setText(QCoreApplication::translate("MainWindow", "...", nullptr));
        label_6->setText(QCoreApplication::translate("MainWindow", "category", nullptr));
        lineEdit_2->setText(QString());
        label_5->setText(QCoreApplication::translate("MainWindow", "name", nullptr));
        name_1->setText(QString());
        error1->setText(QCoreApplication::translate("MainWindow", "TextLabel", nullptr));
        comboBox->setItemText(0, QCoreApplication::translate("MainWindow", "True or False", nullptr));
        comboBox->setItemText(1, QCoreApplication::translate("MainWindow", "Multiple Choices", nullptr));
        comboBox->setItemText(2, QCoreApplication::translate("MainWindow", "Identification", nullptr));

        trueBtn->setText(QCoreApplication::translate("MainWindow", "True", nullptr));
        falseBtn->setText(QCoreApplication::translate("MainWindow", "False", nullptr));
        error_msg1->setText(QString());
        a_btn->setText(QCoreApplication::translate("MainWindow", "A", nullptr));
        b_btn->setText(QCoreApplication::translate("MainWindow", "B", nullptr));
        c_btn->setText(QCoreApplication::translate("MainWindow", "C", nullptr));
        d_btn->setText(QCoreApplication::translate("MainWindow", "D", nullptr));
        label_9->setText(QCoreApplication::translate("MainWindow", "Question", nullptr));
        Add->setText(QCoreApplication::translate("MainWindow", "Add", nullptr));
        pushButton_9->setText(QCoreApplication::translate("MainWindow", "Save", nullptr));
        cat->setText(QCoreApplication::translate("MainWindow", "category", nullptr));
        name_2->setText(QCoreApplication::translate("MainWindow", "name", nullptr));
        q_no->setText(QCoreApplication::translate("MainWindow", "question no.", nullptr));
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINWINDOW_H
